####################################
#                                  #
#         TNT Wars Config          #
#                                  #
####################################

Game-Min: 2
Game-Start-30Sec: 4
Game-Queue-Time: 2
Hub:
  world: world
  x: 0
  y: 100
  z: 0
  yaw: 0
Arenas:
  1:
    Name: Main
    Icon: PAPER
    Game-Max: 12
    Players-Per-Team: 6
    lobby:
      world: world
      x: 0
      y: 100
      z: 0
    spectate:
      world: world
      x: 0
      y: 100
      z: 0
    1:
      Icon: PAPER
      Damage: 0
      world: world
      x: 0
      y: 100
      z: 0
    2:
      Icon: PAPER
      Damage: 0
      world: world
      x: 0
      y: 100
      z: 0