####################################
#                                  #
#         TNT Wars Config          #
#                                  #
####################################

Game-Min: 2
Game-Start-30Sec: 4
Game-Max: 12
Game-Queue-Time: 2
Arenas:
  1:
    Name: Main
    Icon: PAPER
    SpawnPoint:
      world: world
      x: 0
      y: 100
      z: 0
    SpecPoint:
      world: world
      x: 0
      y: 100
      z: 0
  2:
    Name: Other
    Icon: PAPER
    SpawnPoint:
      world: world
      x: 0
      y: 100
      z: 0
    SpecPoint:
      world: world
      x: 0
      y: 100
      z: 0