name: TNTWars
version: 1.0
main: me.abandoncaptian.TNTWars.Main
description: TNT Wars made by abandoncaptian
commands:
  tw:
    description: Command for TNTWars
  mod:
  mods:
    description: Command for Mod Chat
  admin:
  admins:
    description: Command for Admin Chat
  owner:
  owners:
    description: Command for Owner, RightHand Chat